### ISSUE TITLE
breadcrumbIgnore and Including The Paths Ignored

### ISSUE THREAD

**Issue by marceux** [nutgaard/react-router-breadcrumbs#149]
Hi,

We have a scenario popping up with our project's breadcrumbs and I wanted to discuss workarounds and potential alternatives.

Within our `routes` file we have the following composition:

```jsx
<Route path=":context" breadcrumbIgnore >
    <Route path="publishers" breadcrumbIgnore >
        <IndexRoute component="PublishersPage" breadcrumbIgnore />
        <Route path=":publisherId" component="PublisherPageContainer" />
        {/** Other Routes **/}
    </Route>
</Route>
```

When I reach the `/:context/publishers/:publisherId` page, it creates a one-link breadcrumb (expected) that points at the following href, `/:publisherId`.

What I would like to do, is to include the paths to the parent routes, but just not include actual links to them.

So it would be a one-link breadcrumb, `:publisherId` that has an href that points to `/:context/publishers/:publisherId`.

Any suggestions?

**Comment by nutgaard** [comment]
Hi, and thanks for opening this issue.

Correct me if I've misunderstood, but the way it works today is that it creates an link with href `/:publisherId` which is not a valid url within your application. Is that a correct understanding?

If so, I feel like this is a bug in the implementation and should be fixed here. 

One workaround for the time being is to collapse down your route-config, e.g use

```
<Route path=":context/publishers" component={PublishersPage} />
<Route path=":context/publishers/:publisherId" component={PublisherPageContainer} />
```
With this configuration it should give you the correct url for link. This does however force you to duplicate large portions of your path, and removes a lot of the benefits of using react-router. E.g nested view are not easy to setup in such a fashion.

I'll label this issue as a bug for now, as it is my understanding that the link points to an invalid url.

**Comment by marceux** [comment]
Hi,

I thought I responded to this comment with my own, but yes, your solution and understanding are both correct. I'm super happy you're such a responsive maintainer, thanks for all your help.

**Comment by nutgaard** [comment]
I'm just happy people are using it. Hopefully it provides some value to you and others. :-)

**Comment by nutgaard** [comment]
1.2.0 released. Bumped minor as it may have an effect on others. Hopefully this resolves any issues you had. :)

Closing this for now, but just reopen the issue if you would like to see other changes related to this.
