### ISSUE TITLE
Can't create Breadcrumb

### ISSUE THREAD

**Issue by GreenAsJade** [nutgaard/react-router-breadcrumbs#20]
From 

`<Breadcrumbs routes={routes}>
`

where routes=this.props.routes, which is an array, I get:

"React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)."

What am I doing wrong?      In the example, I can see the App just grabbing the routes from the props, as I am doing.

**Comment by GreenAsJade** [comment]
My mistake: was an import issue.

**Comment by nutgaard** [comment]
Good to hear it was resolved. 👍
