### ISSUE TITLE
multiple slashes in my createdHref

### ISSUE THREAD

**Issue by alecperkey** [nutgaard/react-router-breadcrumbs#210]
https://github.com/nutgaard/react-router-breadcrumbs/blob/master/src/breadcrumbs.js#L29

This was causing an error ``` Failed to execute 'pushState' on 'History': A history state object with URL 'http://foo/bar' cannot be created in a document with origin http://zzz.com...```

because my link from createHref function was like `//foo/bar`

so I changed

`.replace(/\/\//g, '/');`

to

`.replace(/\/\/+/g, '/');`

**Comment by nutgaard** [comment]
Hi, and thanks for the feedback.

If possible, please submit this as a pull request with some tests to ensure that the library doesn't regress in the future.

**Comment by nutgaard** [comment]
`react-router-breadcrumbs@1.3.0` released. Proposed fix in regex included.
