### ISSUE TITLE
[Question] creating Bootstrap style breadcrumbs

### ISSUE THREAD

**Issue by zRaspina** [nutgaard/react-router-breadcrumbs#222]
Hi @nutgaard , Happy New Year ... 🎄 
I'm using Bootstrap and want to make breadcrumbs that look like below:
```html
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li><a href="#">Library</a></li>
  <li class="active">Data</li>
</ol>
```
Is it possible with your awesome component?
Please guide me?

**/CC:** @marceux

**Comment by marceux** [comment]
@zRaspina 

Hey Friend,

As for your situation, this is how I would handle it...

```
// Custom createLink implementation

function CustomLink(link, key, text, index, routes) {
    return (
        <li key={key}>
            <a href={link}>{text}</a>
        </li>
    );
}
```

```
// in your render/return

<Breadcrumbs
    routes={routes}
    wrappingComponent={'ol'}
    className={'breadcrumb'}
    createLink={CustomLink}
/>
```

**Comment by zRaspina** [comment]
Thanks @marceux ,
I'll checking this man so I close this and if I have a question ask it here again.

**Comment by tedeh** [comment]
I'm also trying to recreate the bootstrap breadcrumbs with this library but I can't seem to figure out how to get the `<li>` for the last breadcrumb to get the `active` class. There is no way that I can see that the `createLink` function can know when it is called to return the last link/crumb. 

Does anyone have any ideas on how to solve this? Thanks!

**Comment by nutgaard** [comment]
Hi, 
if you look at the code for `CustomLink` in @marceux comment you'll see that it receives `index` and `routes`. So you could probably do something like this:

```
function CustomLink(link, key, text, index, routes) {
    const isLastElement = index === routes.length - 1;
    const cls = isLastElement ? '' : 'active';
    return (
        <li key={key}>
            <a href={link} className={cls}>{text}</a>
        </li>
    );
}
```

**Comment by tedeh** [comment]
Thanks @nutgaard but that doesn't seem to work - `routes` seems to me to correspond to every defined route, not just a plain list of every route in the currently matching tree.

**Comment by nutgaard** [comment]
@tedeh That is weird. Could you post your `routes`-config? And which versions of react-router and react-router-breadcrumbs you are using?

The issue you are having is very similar to the open enhancement proposal in #201. 
And I've just verified that routes is in fact an array of the different routes in the matching tree using the example-section.

**Comment by tedeh** [comment]
Hey,
I just checked again to verify and it seems that indeed you are right. There might have been some interference earlier when I was messing around with customization.

Thanks for taking the time.

**Comment by nutgaard** [comment]
Hey, no problem. 👍 

If you encounter any other issues then don't hesitate to create a github-issue.
