### ISSUE TITLE
Support for optional parameters

### ISSUE THREAD

**Issue by guioconnor** [nutgaard/react-router-breadcrumbs#224]
At present, using the optional parameter syntax breaks the breadcrumb link by using the `(` and `)` as a literal character.

https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteMatching.md#path-syntax

For instance, we would expect that...

```<Route path="/hello(/:name)">       // ... matches /hello, /hello/michael, and /hello/ryan```

**Comment by nutgaard** [comment]
Hi, and thanks for reporting this issue.

If I understand correctly; then this can be solved in the library by just removing the `(` and `)` prior to returning the `href` here https://github.com/nutgaard/react-router-breadcrumbs/blob/master/src/breadcrumbs.js#L31

In the meantime I would suggest duplicating your routeconfig, e.g having both paths
```
<Route path="/hello/:name">
<Route path="/hello">
```

**Comment by guioconnor** [comment]
Hi @nutgaard, thanks for the suggestion, however, we are defining one route per view on the route itself and implementing multiple routes would require some re-architecting.

You could manually discard the parentheses before returning, however my colleague @will14smith has submitted a pull request (#228) that fixes the problem in a more elegant way using react-router's own pattern formatter. This way, the module is even future proofed against further path syntax changes.

If you have some time to review the PR and merge it, we would be very grateful, as this is breaking some functionality on our side.

**Comment by nutgaard** [comment]
I actually looked for this kind of feature in `react-router` yesterday, but didn't find it. My bad for giving up to soon. 

I'll take a look at the PR, and try to get it merged in and released during the day.

**Comment by guioconnor** [comment]
Awesome, thanks

**Comment by nutgaard** [comment]
Version `2.0.0` just released to npm. Hopefully this solves your issues. :)

**Comment by guioconnor** [comment]
Thanks @nutgaard, will give it a go and I feed back.
