### ISSUE TITLE
What breaking changes happened to 2.0.0?

### ISSUE THREAD

**Issue by GreenAsJade** [nutgaard/react-router-breadcrumbs#241]
The major version changed, but no Changelog record to tell us why. 

It'd be nice if you could :)

**Comment by nutgaard** [comment]
I should absolutely add a Changelog. My bad. 

The change in 2.x.x was due to #228 which changes how `params` are handled from doing a manual search&replace to using react-routers `formatPattern` which will throw an error if you have non-optional params which is not defined.

**Comment by nutgaard** [comment]
Added changelog and releasenotes.
