### ISSUE TITLE
Duplicated key

### ISSUE THREAD

**Issue by manodupont** [nutgaard/react-router-breadcrumbs#245]
I always have the duplicated key warning

```
Warning: flattenChildren(...): Encountered two children with the same key, `Home`. Child keys must be unique; when two children share a key, only the first child will be used.
    in div (created by Breadcrumbs)
```

can you do something to it ?

**Comment by nutgaard** [comment]
Hi, this is most likely due to something in your routeconfig.  If you post it here, then I can take a look at it.

**Comment by nutgaard** [comment]
No response, and I'm not able to reproduce this without more information.
