### ISSUE TITLE
Question: Different Breadcrumb

### ISSUE THREAD

**Issue by t-hughes** [nutgaard/react-router-breadcrumbs#281]
Is it possible to have a dropdown/select input appear as a breadcrumb rather than text?

**Comment by nutgaard** [comment]
Hi,
yeah it should be possible. 

The `Breadcrumb`-component has a `createLink`-prop which you can use to override how the crumbs are rendered. Here you could return a `select` instead, though you must handle the redirect when the values changes by yourself.

**Comment by t-hughes** [comment]
Perfect! Thank you!

**Comment by nutgaard** [comment]
I'm not really sure I'm following what you trying to do here. 

But the expected type of `createLink` is `(link, key, text, index, routes) => React.Element;` So you could use `index` and `routes.length` to create a select on only the last crumb.

**Comment by t-hughes** [comment]
That is precisely what I needed. Thank you!
