### ISSUE TITLE
react-router-breadcrumbs usingt the deprecated default export from `react-router/lib/PropTypes` 

### ISSUE THREAD

**Issue by GreenAsJade** [nutgaard/react-router-breadcrumbs#34]
Use of this awesome library causes the following console warning:

Warning: [react-router] The default export from `react-router/lib/PropTypes` is deprecated. Please use the named exports instead.warning 

Warning: [react-router] This prop type is not intended for external use, and was previously exported by mistake. These internal prop types are deprecated for external use, and will be removed in a later version.

("react": "^0.14.2",  "react-router-breadcrumbs": "^1.0.12")

**Comment by nutgaard** [comment]
Hi,
thanks for letting me know. I'll take a look at it.

**Comment by nutgaard** [comment]
Issue should be solved by #35 

I've merged and published a new version now. Try bumping your version to 1.0.13

If the warnings persist please let me know.

**Comment by GreenAsJade** [comment]
Confirmed: warnings are gone.  Thanks!
